---
- name: Authorize SSH access for Jenkins
  authorized_key: user=root key="{{ item }}"
  with_file:
    # mind the underscore at beginning of Jenkins' key filename
    - files/keys/_teamred-jenkins-id_rsa.pub
  when: authorize_jenkins

- name: Authorize SSH access for human employees
  authorized_key: user=root key="{{ item }}"
  with_file: "{{ authorized_ssh_keys }}"

- include: ../../../tasks/configure-iptables.yml

- name: Copy test script
  copy: src=files/test-server.sh dest=/root mode=u+rwx
