jenkins_plugins:
  - ace-editor
  - ant
  - antisamy-markup-formatter
  - artifactory
  - branch-api
  - cloudbees-folder
  - conditional-buildstep
  - config-autorefresh-plugin
  - credentials
  - cvs
  - durable-task
  - dynamicparameter
  - email-ext
  - envinject
  - external-monitor-job
  - ghprb
  - git
  - git-client
  - git-server
  - github
  - github-api
  - github-branch-source
  - github-organization-folder
  - gradle
  - handlebars
  - htmlpublisher
  - icon-shim
  - javadoc
  - jenkins-multijob-plugin
  - job-dsl
  - jquery
  - jquery-detached
  - junit
  - ldap
  - mailer
  - mapdb-api
  - matrix-auth
  - matrix-project
  - maven-plugin
  - momentjs
  - node-iterator-api
  - pam-auth
  - parameterized-trigger
  - pipeline-build-step
  - pipeline-input-step
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-view
  - plain-credentials
  - rebuild
  - run-condition
  - scm-api
  - script-security
  - scriptler
  - sonar
  - ssh
  - ssh-agent
  - ssh-credentials
  - ssh-slaves
  - structs
  - subversion
  - token-macro
  - translation
  - vsphere-cloud
  - windows-slaves
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
